### ISSUE TITLE
Dependency Submission - Snapshots not generating Dependency Alerts

### ISSUE THREAD

**Issue by felickz** [octodemo/trivy-sbom-dependency-submission#1]
Added [Trivy post build](https://github.com/octodemo/trivy-sbom-dependency-submission/blob/73ae93e6c5604a3fc6ead19376e2ebd44a4faa5e/.github/workflows/sbom-upload.yml#L26): 
```yml
    - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Snapshots
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'github'
        output: 'dependency-results.sbom.json'
        image-ref: '.'
        github-pat: '${{ secrets.SBOM_PAT }}'
```

https://github.com/octodemo/trivy-sbom-dependency-submission/network/dependencies

![image](https://user-images.githubusercontent.com/1760475/202532913-daca8c6f-ac9c-40e8-8e10-c81beae36ffd.png)
